### ISSUE TITLE
Video inferencing pipelines

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#113]
Some more concrete thoughts on what we were talking about earlier:

Example: https://github.com/intel/video-analytics-serving/tree/e949055afc3144818c93b6a6dc881b014043f93c#example-request

Instead of a curl request, could be replaced with something like
`SELECT ML_PREDICT("yolov4") FROM rikai_dataset_name`

The detection result looks like:

```
{
  "objects": [
    {
      "detection": {
        "bounding_box": {
          "x_max": 0.9022353887557983,
          "x_min": 0.7940621376037598,
          "y_max": 0.8917602300643921,
          "y_min": 0.30396613478660583
        },
        "confidence": 0.7093080282211304,
        "label": "bottle",
        "label_id": 5
      },
      "h": 212,
      "roi_type": "bottle",
      "w": 69,
      "x": 508,
      "y": 109
    }
  ],
  "resolution": {
    "height": 360,
    "width": 640
  },
  "source": "https://github.com/intel-iot-devkit/sample-videos/blob/master/bottle-detection.mp4?raw=true",
  "timestamp": 39553072625
}
```

We'll want to be able to have some entry point to turn the results into Annotation objects (and select just the fields we want).

The complexity here how to create a good API that allow the user to specify some pre-processing pipeline where the input is a video uri and the output is in the format required by the ML_PREDICT model.

And to really make it a good user experience, the declarative annotation framework would come in handy to be able to combine the detections / outputs with the input and create a new video with detections marked. But since that framework might take some time, we can provide some convenience functions in the meantime.

**Comment by eddyxu** [comment]
With #137, we can do

```sql
SELECT video_uri as source, ML_PREDICT(yolov4, video_to_image(video)) FROM dataset
```
