### ISSUE TITLE
Implement a Option class in python

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#134]
So that it can back up a few functionalities:

* Implement helping methods like "getInt, getFloat" and etc.
* Manage serialization between JVM and python to pass configurations and options. 

The same class should be helpful for #15 as well.

**Comment by changhiskhan** [comment]
so what do you think about using the pandas options as a temporary `rikai.options` module for now?
Pro: only a few lines of code
Con: someone might accidentally do pd.reset_option('all') and also clear rikai options.

That can be done to satisfy #15 without doing this issue.

What examples did you have in mind that needs this Option class?

**Comment by eddyxu** [comment]
A few places, for example `pre/post` transforms, `model` are using `Dict[str, str]` to inherent options from model specs. With a config/option class, with the supports of `getInt` `getFloat` and etc, it is easier to manage the configurations.

Also this option needs to be passed between python and spark jvm. i.e, model spec parsed in python , registered to JVM's `ModelCatalog`. When we pass the conf/options, now we serialize them into `Map[String, String]`. But when we use it, need to support more types as well.

**Comment by changhiskhan** [comment]
ic. in that case this doesn't seem super urgent. I might do #15 with the pandas hack for now to provide some mechanism for users to override settings easily. That way i can move onto the mlflow stuff sooner.
