### ISSUE TITLE
Support  Yolo 4/5 in SQL ML

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#137]
Similar to https://github.com/eto-ai/rikai/blob/master/python/rikai/contrib/torch/transforms/fasterrcnn_resnet50_fpn.py,

Implement the pre/post processing procedures for Yolo 4/5. So that we can later use yolo as the model used in SQL ML inference.

**Comment by darcy-shen** [comment]
Yolov5 is available since Rikai v0.0.11.

For example:
https://github.com/da-tubi/rikai-example/blob/master/yolov5_mlflow.py
