### ISSUE TITLE
Support MLFlow model registry

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#138]
Currently we only support a model specified by YAML file on file system. We should support MLflow model registry in SQL ML as well.

https://www.mlflow.org/docs/latest/model-registry.html

The delivery should be that we can use 

```CREATE MODEL foo USING 'mlfow://...``` to integrate SQL ML with MLflow

**Comment by changhiskhan** [comment]
testing webhook

**Comment by YikSanChan** [comment]
Hi, I was introduced to the project by Chang.

I'd like to learn what make you pick ML flow model registry over others? Thanks!

**Comment by eddyxu** [comment]
Hey, @YikSanChan , welcome !

Rikai SQL ML was architecture in a way that is agnostic to different model registries. We'd think that giving mlflow's popularity, supporting it could help to bring the benefits `rikai` to more users directly with less integration work from users.

Happy to chat to discuss more.

**Comment by YikSanChan** [comment]
@eddyxu Thanks for the answer! I will keep watching 👀 Good work!

Will definitely reach out if I have any question.

**Comment by sadhen** [comment]
Welcome!
