### ISSUE TITLE
Implement shortcut for rikai format on spark dataframe I/O

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#172]
Similar to what parquet / cvs/ bigquery, spark's convention allows we to implement reader / writer like

```
spark.read.rikai("path/to/dataset")
spark.write.rikai("path/to/dataset")
```

**Comment by da-tubi** [comment]
Let me implement this one. I'm familiar with how Data Source works in Apache Spark.

**Comment by eddyxu** [comment]
Great, assigned to you!

**Comment by changhiskhan** [comment]
if we're doing the work of creating a new datasource, let's make it so that it can load from a large zip file? e.g., can we have it directly read the coco dataset targz?

**Comment by eddyxu** [comment]
this PR is not a new datasource. 

It is like adding helper functions to https://github.com/eto-ai/rikai/blob/master/src/main/scala/ai/eto/rikai/RikaiRelation.scala
