### ISSUE TITLE
Consolidate transform_fn and collate_fn in torch.DataLoader

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#19]
These two functions are basically the same

https://github.com/eto-ai/rikai/blob/master/python/rikai/torch/data.py#L41-L42

`torch.data.DataLoader` uses `collate_fn` https://pytorch.org/docs/stable/data.html#torch.utils.data.DataLoader

**Comment by changhiskhan** [comment]
I just looked again, the `transform_fn` is applied to a single source record inside the parallel prefetch thread (e.g., for sampling frames from a video) while the `collate_fn` will be applied to a batch of output records out of the queue. Maybe we can change the name and document it better? Do you have a better name suggestion?

**Comment by eddyxu** [comment]
i've seen `transform` somewhere in pytroch doc. 

https://pytorch.org/tutorials/beginner/data_loading_tutorial.html#iterating-through-the-dataset

Can we make them compatible?

**Comment by changhiskhan** [comment]
#62 will kick the can down the road for now
