### ISSUE TITLE
0.0.5 pypi wheel miss rikai.spark.sql.generated module

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#217]
Reproduce:
* Download https://files.pythonhosted.org/packages/ff/f3/a82a666d8a0e52cf7668d3d8d95dc41ed7127382071950deccfa71d52fcb/rikai-0.0.5-py3-none-any.whl
* `unzip -l rikai-0.0.5-py3-none-any.whl`
*

**Comment by changhiskhan** [comment]
ok 0.0.4 had the same issue

**Comment by changhiskhan** [comment]
oh it's because there's no __init__.py so find_packages doesn't see it

**Comment by eddyxu** [comment]
Fixed in #219
