### ISSUE TITLE
CREATE MODEL option can not take integer value

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#222]
Failed to parse 

```
[info] - create model with options *** FAILED ***
[info]   org.apache.spark.sql.catalyst.parser.ParseException: no viable alternative at input 'CREATE MODEL'(line 1, pos 7)
[info]
[info] == SQL ==
[info] CREATE MODEL model_options OPTIONS (foo='bar',num=1.2,batch=10,flag=True) USING 'test://foo'
[info] -------^^^
```

**Comment by changhiskhan** [comment]
likely this is because the parser rule is ambiguous (int vs floating tokens)? not sure if there's some lookahead or decimal mode you can apply? It's been a long time since I last made an ANTLR grammar so i don't remember the details anymore.

**Comment by changhiskhan** [comment]
@eddyxu @sadhen do we need the parser to distinguish between integer and float? 

Here's a sample from the antlr4 book source code
```
NUMBER
    :   '-'? INT '.' [0-9]+ EXP? // 1.35, 1.35E-9, 0.3, -4.5
    |   '-'? INT EXP             // 1e10 -3e4
    |   '-'? INT                 // -3, 45
    ;
fragment INT :   '0' | [1-9] [0-9]* ; // no leading zeros
fragment EXP :   [Ee] [+\-]? INT ; // \- since - means "range" inside [...]
```

**Comment by eddyxu** [comment]
For example, here in spark's `antlr` file

https://github.com/apache/spark/blob/master/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBase.g4#L411-L416

```
tablePropertyValue
    : INTEGER_VALUE
    | DECIMAL_VALUE
    | booleanValue
    | STRING
    ;
```

**Comment by sadhen** [comment]
One possible cause of this problem is that the antlr used to generate Java code and the antlr runtime do not match.

Verified that the antlr versions actually matches. And we'd better explicitly pin antlr in sbt like:

```
antlr4Version in Antlr4 := "4.8-1"
```

**Comment by sadhen** [comment]
A reproducer is prepared: https://github.com/da-tubi/antlr-int

Hopefully, this issue will be solved soon.

**Comment by sadhen** [comment]
Solution:
https://github.com/antlr/grammars-v4/blob/70b7754641de8f575595da61132da4583c7de100/c/C.g4#L599:L621

Bug:
https://github.com/eto-ai/rikai/blob/c69f8169882879026f8d91fac7d885aed09c968e/src/main/antlr4/org/apache/spark/sql/ml/parser/RikaiExtSqlBase.g4#L84:L87
