### ISSUE TITLE
prefetch has no effect in ML_PREDICT?

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#265]
the preprocessor is passed into PandasDataset https://github.com/eto-ai/rikai/blob/master/python/rikai/spark/sql/codegen/pytorch.py#L60
but the prefetching happens after in DataLoader: https://github.com/eto-ai/rikai/blob/master/python/rikai/spark/sql/codegen/pytorch.py#L62

by then uri_to_pil would have already been called.

@eddyxu  didn't we used to pass pre_processing to DataLoader as the collate_fn? I forgot why we don't do that anymore

**Comment by eddyxu** [comment]
PandasDataset is implemented as a map style dataset https://github.com/eto-ai/rikai/blob/master/python/rikai/torch/pandas.py#L51-L56

The transform (i.e., uri_to_pil) should be called when `dataset[i]` is called, which should be called in multiprocess env in torch dataset loader.
