### ISSUE TITLE
tmp_s3_path as fixture to enable S3 based tests

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#304]
For s3 related tests, we can offer user a tmp path on s3, to read and write dataset.

It can work as pytest [fixtures](https://docs.pytest.org/en/6.2.x/fixture.html)

And skipped via certain marks or environment variables.

**Comment by changhiskhan** [comment]
so by default this fixture will have nothing and then we need to populate the path and the credentials via env var and then the mark can enable/disable related tests?
