### ISSUE TITLE
Upgrade minimal pytorch version to 1.9

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#342]
We can use torch 1.8's DataLoader and remove the DataLoader from `rikai.torch.data.DataLoader`

**Comment by Renkai** [comment]
@eddyxu Do we need to keep these two tests(`test_load_dataset` and `test_load_dataset`) after we remove the class `rikai.torch.data.DataLoader`?


https://github.com/eto-ai/rikai/blob/88541f3140352161f9647c7f0caa5abfaac65442/python/tests/torch/test_data.py#L31

**Comment by Renkai** [comment]
For new `Dataloader` after pytorch 1.9, is `test_torch_dataset` enough?

**Comment by eddyxu** [comment]
Thanks for working on this, @Renkai .  Lets use `torch.data.DataLoader` in `test_load_dataset` to verify the compatibility between rikai dataset and torch DataLoader?

**Comment by Renkai** [comment]
upgraded to 1.8, will create a ticket again when the newest Databricks Runtime is prepared for 1.9.
