### ISSUE TITLE
udf: inspect_bbox

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#355]
See

+ https://github.com/eto-ai/rikai/blob/v0.0.12/notebooks/Coco.ipynb
+ https://github.com/da-tubi/rikai-example/blob/main/yolov5_video.ipynb

**Comment by changhiskhan** [comment]
do we still want this @darcy-shen ?

**Comment by darcy-shen** [comment]
We do not need this UDF any more.
