### ISSUE TITLE
Diagnose performance issue

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#365]
We had a dataset of about 900 images which took 2.24 min to churn through ML_PREDICT. If we just manually write a for-loop in python over the json form of the same dataset and apply the model, it takes about 5s.

Current suspect is that the performance issue comes from the model being each time we invoke the ML_PREDICT pandas_udf.

**Comment by changhiskhan** [comment]
@da-tubi do you remember how you partitioned that dataframe and what did you set the batch size to? Would you or @Renkai be able to confirm the cause? e.g., time the model load time and confirm how many times the pandas_udf was invoked?

**Comment by da-tubi** [comment]
Processing 1377 frames on GPU took 4.82 min to complete (including write the data to parquet).
```
%sql
CREATE OR REPLACE MODEL logo_sample_m 
PREPROCESSOR 'rikai_ext.yolov5.pre_processing'
POSTPROCESSOR 'rikai_ext.yolov5.post_processing'
OPTIONS (
  num_workers=0,
  batch_size=1,
  device='gpu'
)
USING 'mlflow:///logo_detection';

create table tmp.da_preds as
from (
  from tmp.da_video_frames
  select
    video_uri,
    frame_id,
    ts,
    image_data,
    ML_PREDICT(logo_sample_m, image_data) as pred
)
select *
where size(pred.boxes) > 0
```

**Comment by da-tubi** [comment]
cache tmp.da_video_frames in memory, we could reduce the time from about 5 minutes to 1.65 minutes

**Comment by darcy-shen** [comment]
Now it costs about 10 seconds to process a 30-seconds video.

**Comment by da-tubi** [comment]
https://github.com/eto-ai/rikai/issues/367 and https://github.com/eto-ai/spark-video/issues/14 would be helpful to improve performance!

**Comment by da-tubi** [comment]
cache tmp.da_video_frames in memory and repartition it in only one partition.

The total time could be reduced.

| tmp.da_video_frames | total frames | total time |  frames per second | how many seconds for 150 frames |
| S3 | 1377 | about 5m | | |
| memory (2 partition) | 1377 | 1.57m | 14 | 10  |
| memory (1 partition) | 1377 | 1.24m |  |  |

**Comment by da-tubi** [comment]
![image](https://user-images.githubusercontent.com/66561265/143404415-97b0e405-1062-4532-80a7-ca7ec2c4d613.png)

Using Rikai 0.0.12 with https://github.com/eto-ai/rikai/pull/361 patched.

**Comment by changhiskhan** [comment]
I think this is good now
