### ISSUE TITLE
Dataset resolver

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#366]
Currently users are required to provide the full dataset path in order to instantiate a Rikai pytorch Dataset/DataLoader.
e.g., from the rikai README:

```
from rikai.torch.vision import Dataset
from rikai.torch import DataLoader # Do not need this with Pytorch 1.8+
from torchvision import transforms as T

transform = T.Compose([
   T.Resize(640),
   T.ToTensor(),
   T.Normalize((0.485, 0.456, 0.406), (0.229, 0.224, 0.225))
])

dataset = Dataset(
   "s3://path/to/features",
   columns=["image"],
   transform=transform
)
loader = DataLoader(
    dataset,
    batch_size=32,
    shuffle=True,
    num_workers=8,
)
for batch in data_loader:
    predicts = model(batch.to(cuda))
```

Instead, we want the user to be able to refer to a dataset directly by name if a data catalog is available to resolve the references to a parquet directory.
Note that in an environment where Spark is available and the data catalog is the hive metastore, one *could* do something like
```
dataset = Dataset(sqlContext.table('table_name'), ...)
```
So the user doesn't have to remember the full path. However, Spark is not always available, the user still has to remember the appropriate Spark syntax each time, and also we would have to write the DataFrame to disk first.

First option:
1. we create a simple `DatasetRefResolver` interface with a simple `resolve_dataset_uri` method.
2. The implementation to use can be configured in rikai.options
3. the default resolver will have the following behavior:
    a. If the reference is a full uri with a scheme prefix, then assume it's a direct reference
    b. Else if the reference is a simple string and we're in a spark context then try to use the spark catalog (HMS)
    c. Else if the reference is a DataFrame, then write the dataframe to disk and use the directory the data was written to.

Second option:
1. We create a new resolver implementing BaseResolver in `rikai.parquet.resolver` that's HMS-aware. We then register this with the Resolve class for when there is no scheme.

**Comment by eddyxu** [comment]
Not clear to me whether option 1 and 2 are the same actually.  Giving the pre-0.1 status of rikai, `BaseResolver` can change its interface to be option 1? or vise versa.  I'd lean to consolidate them into just one. 

So for `3.c`,  the `DataFrame` can be either a Spark DataFrame or a pandas DataFrame? If it is still in the memory (i.e., as `pd.DataFrame`), we might not need to write them to directory first?
