### ISSUE TITLE
Prepare scala 2.13 build

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#380]
Spark 3.2 starts to support scala 2.13. 

We can start to build rikai with both scala 2.12 & 2.13

**Comment by da-tubi** [comment]
See #337 .

**Comment by eddyxu** [comment]
I see. while I understand it is possible to build scala 2.12 & 2.13 in the same repo. Is it possible to build with Spark 2.12 & 2.13 ?
@da-tubi

**Comment by da-tubi** [comment]
Yes. See https://github.com/NVIDIA/spark-rapids/tree/branch-22.02/sql-plugin/src/main

**Comment by eddyxu** [comment]
already done in #337
