### ISSUE TITLE
Upload the assembled jar to release

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#386]
Currently, I'm manually create the assembled jar: https://github.com/da-tubi/rikai/releases/tag/v0.0.12

**Comment by changhiskhan** [comment]
https://github.com/sbt/sbt-assembly#publishing-not-recommended

do you need the uber jar because of download speeds outside of VPN?

**Comment by darcy-shen** [comment]
I think publishing to Maven repo is much better. Because it is immutable. On github, there is still security concerns. Eg. One of the Github account is hacked.

I need to work on #588  first and then work on this ticket.

Can I become the release manager for the next Rikai release?

**Comment by darcy-shen** [comment]
With the PR (#625), it will be published by `sbt publishLocal`. No need to be a release manager to debug github action CI.
