### ISSUE TITLE
Deprecated circe and use jackson shipped by Apache Spark

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#417]
```
$ git grep "io.circe"
build.sbt:    "io.circe" %% "circe-core" % circeVersion,
build.sbt:    "io.circe" %% "circe-generic" % circeVersion,
build.sbt:    "io.circe" %% "circe-parser" % circeVersion,
src/main/scala/ai/eto/rikai/sql/model/Model.scala:import io.circe.syntax._
src/main/scala/ai/eto/rikai/sql/model/Model.scala:import io.circe.generic.encoding.DerivedAsObjectEncoder._
```

in minimalist style, remove third party dependencies as much as possible.

**Comment by darcy-shen** [comment]
circe is only used in Model for processing json, how about remove it? @eddyxu 

In this way, new Rikai user can be freed from downloading circe and cats when launching PySpark. Also, cats lovers could use the latest version of cats with Rikai.

**Comment by eddyxu** [comment]
sure, lets do it
