### ISSUE TITLE
Support Apache Spark 3.2.0

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#421]
For the Scala side, #337 had made it work for Spark 3.2.0.

For the Python side, we still need to make minor changes.

## Watch
+ [x] Databricks Runtime 10.x: https://docs.databricks.com/release-notes/runtime/10.0.html
+ [ ] AWS EMR: https://docs.aws.amazon.com/emr/latest/ReleaseGuide/emr-release-components.html
+ [ ] DataProc: https://cloud.google.com/dataproc/docs/concepts/versioning/dataproc-versions

**Comment by Renkai** [comment]
I will work on the Python compatibility of spark 3.2.0
