### ISSUE TITLE
ImageDraw broken on Jupyter Notebook

### ISSUE THREAD

**Issue by da-tubi** [eto-ai/rikai#462]
due to #434 

Here is the notebook to reproduce it: https://github.com/da-tubi/rikai-example/blob/39ab170546ca7c6f7b66787aff4a36ccb9fa01d8/elephants_dream.ipynb

Actions:
+ Fix it and test it on Jupyter Notebook and Databricks Notebook
+ Add unit tests on _repr_mimebundle_

**Comment by changhiskhan** [comment]
how so?

**Comment by changhiskhan** [comment]
i checked last night after the release went out and it worked ok for me. can you add more details here?

**Comment by da-tubi** [comment]
Your response is too quick! I just created the issue and had not update the description :)

**Comment by da-tubi** [comment]
Here is the code snippet to reproduce the bug:
``` python
from rikai.types.vision import Image
from rikai.types.geometry import Box2d
image = Image(Image.read('/path/to/dog.jpg').data) 
image | Box2d(10, 10, 200, 200)
```
