### ISSUE TITLE
Support torchextractor for pytorch codegen

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#465]
https://github.com/antoinebrl/torchextractor

```
input -> layer1 -> layer2 -> layer3 -> layerN -> output
```

TorchExtractor can be used to get the intermediate result of the specified layer via layer name.

**Comment by eddyxu** [comment]
Can you elaborate more about the context? this lib seems not maintained and not widely use to be a common community practice?

**Comment by darcy-shen** [comment]
It is a request from ML engineers at Tubi. I will try to create a customized flavor to suit their needs first. And then, organized code will be contributed back to Rikai.

**Comment by darcy-shen** [comment]
With ModelType, ML engineers can now extract the middle layer of a model and then apply it to large scaled data by themselves.
