### ISSUE TITLE
Create attribute access UDFs for Rikai Spark UDTs

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#489]
use case is say I want to return the image uri so i can use Mode/Periscope to render images, right now that is impossible.

Probably the easiest is for each UDT to implement a `to_dict` method as part of a RikaiUDT mixin and then we just need to register a single `to_struct` UDF that checks whether the input is RikaiUDT type and then call `to_dict`

@Renkai this is another good one if you're looking for something to get started on

cc @eddyxu wdyt?

**Comment by eddyxu** [comment]
What is the execution environment? if we are talking about SQL, it falls into this issue

https://github.com/eto-ai/rikai/issues/332

#332 is very nice feature to work on @Renkai

**Comment by darcy-shen** [comment]
I can spend my last week before the Chinese New Year on #332 . I don't know if I can fix it in one week.

**Comment by changhiskhan** [comment]
dupe of #332
