### ISSUE TITLE
Implement ModelType interface for more torchvision models

### ISSUE THREAD

**Issue by changhiskhan** [eto-ai/rikai#551]
Currently we have `SSD` and `fasterrcnn` implemented for object detection (https://github.com/eto-ai/rikai/tree/main/python/rikai/pytorch/models)

To make it easier for pytorch users, we should consider implementing additional models from (https://pytorch.org/vision/stable/models.html). At the very least, we should have 2 or 3 image classification models, and 1 video classification model implemented.

**Comment by darcy-shen** [comment]
Hint: `apply_model_spec` can be used to developing ModelType:

https://github.com/eto-ai/rikai/blob/c300eeede0a19c798b70bf7466e1faf0a482a092/python/rikai/testing/utils.py#L60-L67

**Comment by eddyxu** [comment]
Closed via #606
