### ISSUE TITLE
Pin scenedetect < 0.6

### ISSUE THREAD

**Issue by Breakthrough** [eto-ai/rikai#570]
Hi there! I'm the author of PySceneDetect (scenedetect package), and noticed that you haven't pinned the dependency. The next release (v0.6) is slated to include some breaking changes to improve the API usage, so I would recommend that you pin your version to scenedetect < 0.6, otherwise the current source code will break once that is released.

For how your project uses the library in subtitld/modules/file_io.py, it would be just one-line function in the new version ([example](http://scenedetect.com/projects/Manual/en/v0.6/api.html#quickstart)).  The new version will also be multithreaded so will run much faster.  Thank you!

**Comment by changhiskhan** [comment]
Thanks @Breakthrough for the heads-up. When's the next release for pyscenedetect going to come out?

**Comment by Breakthrough** [comment]
There's a beta out now, so if all goes smoothly should have the new release out by the end of this month.

Also one last thing to note, the default threshold was changed from 30 down to 27 as per issue Breakthrough/PyScenedetect#246.  I noticed you had [stored that same value](https://github.com/eto-ai/rikai/blob/4beadf12768ae9201772f180fbbe7ab95c496575/python/rikai/contrib/video/functions.py#L75), so you may also want to lower it to be slightly more sensitive.  This isn't required though, and do note that it would cause behavioural differences.

Thanks!
