### ISSUE TITLE
Assembly dependencies cleaning

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#588]
## Remove cats and shapeless, we will reduce half of the assembly jar size
See https://github.com/eto-ai/rikai/pull/419

## Remove Scala Standard Library
<img width="467" alt="image" src="https://user-images.githubusercontent.com/1267865/160222611-e14e0b89-f3a1-4162-b19f-1e7c051b89bb.png">

## Remove antlr4 (use the Spark built-in one)
<img width="538" alt="image" src="https://user-images.githubusercontent.com/1267865/160222676-178cbd6f-ebca-4147-8a7e-162b2de07313.png">

**Comment by Renkai** [comment]
Interesting, why cats and shapeless are in rikai now?

**Comment by darcy-shen** [comment]
I think reducing the dependencies is an effective way to protect our natural environment as a human being on earth.

**Comment by Renkai** [comment]
@darcy-shen What tools have you used to get this pic? I want to try it locally.
![image](https://user-images.githubusercontent.com/3381789/162195914-adafae7c-65b8-4a56-a342-0147e927d9a8.png)
