### ISSUE TITLE
After making maven release, clean up doc references to the library name

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#59]
We have used `ai.eto.rikai:rikai`, `ai.eto:rikai` `ai.eto:rikai-core`,  as well as `0.0.1` and `0.0.1-SNAPSHOT` in versions.

Once we finalized the package names, we should go over documents to make sure they are correct.

**Comment by eddyxu** [comment]
Also in notebooks

**Comment by changhiskhan** [comment]
I think I had `ai.eto:rikai-core` somewhere in case later on we want to have private rikai-analytics rikai-featurestore jars, but I'm flexible.

**Comment by changhiskhan** [comment]
#63
