### ISSUE TITLE
New Flavor: dummy

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#604]
dummy flavor is for ML inference as a service.

For example, AWS Rekognition (#578) should use dummy flavor because applying ML inference is as easy as a python API call.

And for well-wrapped ML python packages, they hide the details of downloading the pretrained model, loading the model and applying the model for inferencing. For these well-wrapped frameworks, dummy flavor can also be used.

Using dummy flavor, to apply ML model services, just impl the ModelType like the normal model. Rikai will help us hide the details of PySpark Pandas UDF.

**Comment by changhiskhan** [comment]
Don't we already have this via DummySpec?

**Comment by eddyxu** [comment]
is this a user-facing flavor or just a base class to implement other flavors?

```CREATE MODEL <name> FLAVOR dummy ``` seems to be aggressive in english?

**Comment by darcy-shen** [comment]
Here is the sample impl and usage: https://github.com/da-tubi/rikai-ocr/blob/main/rikai/contrib/dummy/codegen.py

> is this a user-facing flavor or just a base class to implement other flavors?

In the ocr demo repo, it is a user-facing flavor. And it could be used as the base class to implement other flavors.

> CREATE MODEL <name> FLAVOR dummy seems to be aggressive in english?

Yes. I think `CREATE MODEL <name> MODEL_TYPE keras_ocr` might be a better syntax.

**Comment by eddyxu** [comment]
We will use more specific flavor name
