### ISSUE TITLE
Coding style: the order of width and height

### ISSUE THREAD

**Issue by darcy-shen** [eto-ai/rikai#610]
There are two different code styles in Rikai:
1. width first, (width, height)
2. height first, (height, width)

For me, I prefer width first. We should unify the coding style.

**Comment by eddyxu** [comment]
Let's make them consistent with width/height?

https://elementarymath.edc.org/resources/measurement-length-width-height-depth/

**Comment by darcy-shen** [comment]
It is a breaking API change, let us change the order for Rikai 0.2.0.
