### ISSUE TITLE
Deprecate python 3.7

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#616]
Major runtimes are move away from python 3.7

- [x] AWS EMR
- [x] Google DataProc
- [x] Databricks Runtime 10+
- [x] Bump setup.py 's python version. update README

**Comment by darcy-shen** [comment]
I disabled github action for Python 3.7 in #623. Because we have too much cache, to be under the max cache size (10G), deprecate Python 3.7 is a good idea.
