### ISSUE TITLE
Optimize release process

### ISSUE THREAD

**Issue by eddyxu** [eto-ai/rikai#69]
Current release process involves a few manual steps

1. change scala version "-SNAPSHOT" to `non-SNAPSHOT`
2. Release jars to sonotype
3. Bump scala code version to "{current + 1}-SNAPSHOT"
4. Modify python tests reference to it.
5. Change python version from ".dev" to non-dev.
6. make `pypi` release.
7. Change python version to "{current + 1}.dev"

All these steps are tedious and easy to break.  We should have a better automatic process. It'd be better to be trigger on Github Actions based on git tags.

**Comment by changhiskhan** [comment]
1. Setup two workflows, one for python and another for sbt release. Both triggered on tag
    - https://github.com/olafurpg/sbt-ci-release
    - https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
2. Setup pypi, testpypi, and sonatype secrets in github
3. Script to bump both versions and add a tag if necessary (use bump2version + custom script for version.sbt ? )

**Comment by changhiskhan** [comment]
Here was the process for v0.0.4 release:
```
Github: make sure head of master is green
Locally: git checkout master, git pull, make release
Locally: make fix, cd python && pytest
Locally: git log (check tag is there)
Locally: git push origin master —tags
Github: wait for new master commit to be green
Github: make new release (select existing tag, just check the commit is the right one)
Github: check the 2 release workflows finished
PYPI: check new version is there
Sonatype: oss.sonatype.org (check rikai new version has been published)
Maven central: check new jar is there (may take a few hours)
```

Future work:
1. Potentially could add another manually triggered workflow to encapsulate 1-7
2. in addition, we’ll need to all make release take in a new version argument. Right now it just bumps the patch version up which won’t work when we want to release 0.1
3. last thing is I am concerned about having the jar up after the python package
during the few hours if people are pulling the new python version but the new jar isn’t showing up then that’s going to be bad

**Comment by changhiskhan** [comment]
Once everything is good, `make patch` creates the next dev0 version.
