### ISSUE TITLE
Can we bump the version of `antlr4-python3-runtime`?

### ISSUE THREAD

**Issue by dnnspark** [eto-ai/rikai#706]
Hello!

Just asking: is there a reason that the version of `antlr4-python3-runtime` is pinned to `4.8` (https://github.com/eto-ai/rikai/blob/main/python/setup.py#L69)? I have seen multiple times that this conflicts with other libraries. Current stable version of that library is `4.11.1`.  I believe upgrading to at least `4.9` would help a lot.

**Comment by changhiskhan** [comment]
Yeah we can definitely update the version. It's pinned mainly so we don't get surprise breakage when antlr updates. Can definitely take a look.

**Comment by changhiskhan** [comment]
@dnnspark please see #707 for the PR to upgrade to 4.11.1  does this solve your issue? If so we'll look to make a bugfix release this week or next.

**Comment by dnnspark** [comment]
@changhiskhan  Yes!  This solves my issue. Thank you very much! Looking forward to the next release.

**Comment by changhiskhan** [comment]
hi @dnnspark we made a new release with the changes you requested. Lmk if everything still works as you expected. If it's easier, happy to continue over email to discuss in more detail (chang@eto.ai)
